### PR TITLE
fix: add dracula theme preview to readme

### PR DESCRIPTION
**Pull request by Trollwut**
Adds a Dracula theme preview to the readme.

You might want to make another preview with your standard wallpaper and environment to fit into the rest of the previews :)

Also tip for future: create a (closed) issue and add your images there. This way you get a reliable link to your image without wasting space in your repo :>

### CODE REVIEW

**Comment by awlbe** [comment]
Nice tip, will try later.

**Comment by Trollwut** [comment]
> Nice tip, will try later.

TBH it's too late for now, as these images are now in the git history. So for this example, users would need to download 6 MB in pictures, which are not important for the project itself (which isn't a problem at all, but you know, there's always something to improve :) ).

Learned this also because someone gave me this tip :D

**Comment by murlakatamenka** [comment]
@Trollwut what's the bar used on the screenshot? Looks slick!

Sorry for offtopic.

**Comment by Trollwut** [comment]
@murlakatamenka thanks! :) it's polybar and I tried to do a Dracula-themed version of it.

I tried to do one that only shows information, if it's necessary. E.g. in the top-right would be a temperature indicator that only shows (in red) if the CPU temp rises above 80°C. Also in the bottom-middle there would be a player indicator only if e.g. Spotify is running. It's not perfect, but I might release some dots if you're interested in it.

**Comment by murlakatamenka** [comment]
I'll be fine with just a stub to hack on. I like how stuff is organized into groups, their slant borders and how they are separated :+1: 

Thanks in advance.

**Comment by Trollwut** [comment]
Here you go mate: https://github.com/Trollwut/dotfiles-polybar-dracula

Be aware that you might install additional software and fonts to make it work. For that I made a dependency file and I hope I got everything what's needed. :D Also I use the font "Germania One", which I downloaded/installed via the tool `fontfinder` (also in AUR).

Hope this helps you!

**Comment by murlakatamenka** [comment]
Thank you, much appreciated!

**Comment by Trollwut** [comment]
Of course mate! I'm far away of being a polybar crack, so if you have any additions to it, hit me up by my mail trollwut_@_trollwut.org (without the underscores).

Now let's rest this issue in peace :)

**Pull request merged**
